name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up GCC for compilation
    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    # Step 3: Build the project
    - name: Build the Project
      run: |
        make clean
        make all

    # Step 4: Run the tests
    - name: Run Tests
      run: ./bin/test_main

    # Step 5: (Optional) Static Code Analysis
    - name: Run Cppcheck
      run: cppcheck --enable=all --inconclusive --std=c99 --quiet src/

    # Step 6: Upload Binaries (Optional)
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/
