name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the environment (install dependencies)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc cppcheck

      # Step 3: Compile the project
      - name: Build the project
        run: |
          gcc -o main src/main.c src/library.c test/test_main.c
          ls -la  # List files to verify the build

      # Step 4: Run tests
      - name: Run tests
        run: ./main

      # Step 5: Perform static code analysis with cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --quiet src/ include/
